export type ImprovementType = 'grammar' | 'style' | 'clarity' | 'coherence' | 'conciseness';

export type ImprovementSuggestion = {
  id: string; // Unique ID for this suggestion
  paragraphIndex: number; // Index of the paragraph in the document
  chapterTitle?: string; // Chapter/section this belongs to
  originalText: string; // Original text
  improvedText: string; // Suggested improved text
  reason: string; // Why this improvement is suggested
  type: ImprovementType; // Type of improvement
  confidence: number; // 0-1, how confident the AI is about this suggestion
};

export type DocumentStructure = {
  sections: Array<{
    title: string; // Chapter/section title
    level: number; // 1 = H1, 2 = H2, etc
    startParagraphIndex: number;
    endParagraphIndex: number;
    paragraphCount: number;
  }>;
  totalParagraphs: number;
  totalChapters: number;
};

export type GlobalContext = {
  title?: string; // Document title
  abstract?: string; // Document abstract/summary
  theme: string; // Main theme/subject (generated by AI)
  chapters: string[]; // List of chapter titles
  chapterSummaries?: Array<{ title: string; summary: string }>; // Summary of each chapter
  objective?: string; // Document objective (generated by AI)
};

export type ImprovementProgress = {
  status: 'pending' | 'analyzing' | 'completed' | 'error';
  currentSection: number;
  totalSections: number;
  percentage: number;
  error?: string;
};

export type ImprovementJob = {
  id: string;
  document_id: string;
  status: 'pending' | 'analyzing' | 'completed' | 'error';
  global_context?: GlobalContext;
  document_structure?: DocumentStructure;
  suggestions: ImprovementSuggestion[];
  current_section: number;
  total_sections: number;
  progress_percentage: number;
  error_message?: string;
  created_at: string;
  started_at?: string;
  completed_at?: string;
};

export type ImprovementOptions = {
  provider: 'openai' | 'gemini'; // AI provider
  model: string; // Model to use
  focusAreas?: ImprovementType[]; // Specific areas to focus on (default: all)
  maxSuggestions?: number; // Max suggestions per section (default: unlimited)
  onProgress?: (progress: ImprovementProgress) => void;
  onLog?: (message: string) => void;
};
